### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by IdioGuarino** [cybersecsi/robodroid#1]
**Describe the bug**

when I try to install the package via pipx, I get the same error message:

Traceback (most recent call last):
  File "/usr/bin/pipx", line 11, in <module>
    load_entry_point('pipx==0.12.3.1', 'console_scripts', 'pipx')()
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 496, in cli
    exit(run_pipx_command(parsed_pipx_args, binary_args))
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 147, in run_pipx_command
    commands.install(
  File "/usr/lib/python3/dist-packages/pipx/commands.py", line 312, in install
    if venv.get_venv_metadata_for_package(package).package_version is None:
  File "/usr/lib/python3/dist-packages/pipx/Venv.py", line 65, in get_venv_metadata_for_package
    data = json.loads(
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'

**Work environment**

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version                 |       Ubuntu 22.04                                |
| Python version             |             Python 3.9                          |
| Device Type                |                                       |
| Android Version            |                                       |

**To Reproduce**

pipx install --force robodroid

**Comment by IdioGuarino** [comment]
I have solved it. Sorry for the issue
